import React, { useState } from "react";
import Head from "next/head";
import Hero from "./Components/Hero";
import Navbar from "./Components/Navbar";
import Display from "./Components/Display";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Crypto Hero</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Navbar />
      <Hero />
      <Display />
    </div>
  );
}
